### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by gtrubach** [Azure/setup-kubectl#12]
Hello,

As I understand this action does not support ARM since there is amd64 hardcoded in download URLs. Is it possible to make this work with ARM (ideally is should decide the arch based on the arch where it's running)?

**Comment by ds-ms** [comment]
@gtrubach would you be willing to raise a PR for the same? 

The logic can be same as https://github.com/Azure/k8s-deploy/pull/117

**Comment by gtrubach** [comment]
@ds-ms - sure, let's finalize the PR first and then I will do the same here.

**Comment by gtrubach** [comment]
@ds-ms - I'm ready to create the same PR here, but it would be cool if this PR https://github.com/Azure/setup-kubectl/pull/13 will be merged first. In that case I'll extend tests with arch cases.

**Comment by ds-ms** [comment]
@gtrubach The tests are added: https://github.com/Azure/setup-kubectl/pull/15 
You can get started with the changes here :)
