### ISSUE TITLE
add kubectl to PATH

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/setup-kubectl#3]
I think it would be handy to add the tool to PATH like in https://github.com/evryfs/cloudctl-action/blob/master/src/main.ts#L30

**Comment by joesteffee** [comment]
+1. This is causing the utility to not be found on self-hosted runners for github actions.

**Comment by bkalcho** [comment]
still experiencing path not found for `kubectl` with `v2.1`:

    | kubectl apply -n kube-system --kubeconfig ./kubeconfig -f -': exit
    │ status 127. Output: /bin/bash: line 23: kubectl: command not found
