### ISSUE TITLE
Please provide an example of how to use this to execute kubectl commands against AKS

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/setup-kubectl#50]
This is great and all, but there's no information on how to use this to successfully use kubectl commands without getting authentication prompts in your actions logs (which hangs the actions)

**Comment by OliverMKing** [comment]
Hi! Please consult our starter workflows for information on how to do this. Our aks-set-context action in particular is what you need to use.

https://github.com/actions/starter-workflows/blob/main/deployments/azure-kubernetes-service.yml
