### ISSUE TITLE
Bug: Action causes deprecated 'set-output' command warning

### ISSUE THREAD

**Issue by xersiee** [Azure/setup-kubectl#69]
### What happened?

Using `azure/setup-kubectl@v3.0` causes the GHA complain about usage of deprecated `set-output` command. Its probably coming from one of the dependencies which could be upgraded.

### Version

- [X] I am using the latest version

### Runner

-

### Relevant log output

Run azure/setup-kubectl@v3.0
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by OliverMKing** [comment]
@xersiee thanks for the issue. We are working on this and will get this out soon.

**Comment by TheQueenIsDead** [comment]
Looks like a fix ([Bumping core to >= v1.10.0](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows)) was merged 14 days ago in https://github.com/Azure/setup-kubectl/pull/68

Any chance a new tag can be published to make this consumable @OliverMKing ?

**Comment by OrBin** [comment]
Any news about a bugfix release?

**Comment by OliverMKing** [comment]
I'll kick off a release today.

**Comment by OliverMKing** [comment]
`v3.1` (and `v3`) have this fix and have been released. Thanks!
