### ISSUE TITLE
Action is failing to install kubectl due to wrong URL

### ISSUE THREAD

**Issue by fasmat** [Azure/setup-kubectl#74]
I've been trying to install version 1.23.15 (and all other 1.23.x) versions using this action but it always fails to download the tool.

It tries to download kubectl from the following URL:

https://github.com/Azure/setup-kubectl/blob/2eb2a370ffe43e1304c195fc41337b39c9757a0f/src/helpers.ts#L16

which doesn't seem to be correct. Instead it should be:

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux

**Comment by nevetS** [comment]
I created a PR to address this issue.  The download location moved away from storage.googleapis.com a while back.  https://www.downloadkubernetes.com has the proper URLs (as referenced in the kubernetes documentation here https://kubernetes.io/releases/download/

**Comment by OliverMKing** [comment]
I went ahead and released this in v3.2 (and v3). Thanks for the issue and help!
