### ISSUE TITLE
unable to find version `v3`

### ISSUE THREAD

**Issue by fishuke** [Azure/setup-kubectl#79]
Error: Unable to resolve action `Azure/setup-kubectl@v3`, unable to find version `v3`

**Comment by OliverMKing** [comment]
@fishuke is this still happening? I'm not able to [replicate](https://github.com/OliverMKing/AKS-GitHub-Actions-Demo/actions/runs/3877445649/jobs/6612468102).

**Comment by fishuke** [comment]
It's fine now thanks...
