### ISSUE TITLE
use new add-path method

### ISSUE THREAD

**Issue by lukemarsden** [Azure/setup-kubectl#8]
I get the following warning using this now:
> Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

For path `$p`, the required behavior change is akin to:
```
-          echo "::add-path::$p"
+          echo "$p" >> $GITHUB_PATH
```

**Comment by sripberger** [comment]
Also seeing this warning. Interally this action uses @actions/core from npm, which addressed this in v1.2.6. Just needs to be updated in this repo.

https://github.com/actions/toolkit/blob/4f7fb6513a355689f69f0849edeb369a4dc81729/packages/core/RELEASES.md#126
