### ISSUE TITLE
Error: Kubectl '1.25.11' for 'amd64' arch not found.

### ISSUE THREAD

**Issue by dkirrane** [Azure/setup-kubectl#87]
This issue just started happening for me `Error: Kubectl '1.25.11' for 'amd64' arch not found.`
I've also tried switch to latest

```
        uses: azure/setup-kubectl@v3
        with:
           version: latest
```

and hit same
Error: Error: Kubectl 'v1.28.3' for 'amd64' arch not found.

**DEBUG**
```
##[debug]isExplicit: 1.25.11
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/kubectl/1.25.11/x64
##[debug]not found
##[debug]Downloading https://dl.k8s.io/release/1.25.11/bin/linux/amd64/kubectl
##[debug]Destination /home/runner/work/_temp/7938a0d6-c4fb-458d-9160-f828d656f77e
##[debug]Failed to download from "https://dl.k8s.io/release/1.25.11/bin/linux/amd64/kubectl". Code(404) Message(Not Found)
Error: Error: Kubectl '1.25.11' for 'amd64' arch not found.
```

**Comment by thecodeassassin** [comment]
Somehow the stable.txt here:

https://storage.googleapis.com/kubernetes-release/release/stable.txt

returns a version that doesn't exist on their gcs bucket.

temporary fix:

      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.2'
