### ISSUE TITLE
please create a V4 with support for node20 instead of relying on node16 which is deprecated

### ISSUE THREAD

**Issue by maapteh** [Azure/setup-kubectl#92]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/setup-kubectl@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

See PR #90

**Comment by davidgamero** [comment]
v4 has been released with the suggested updates, thank you for the contribution!

**Comment by maapteh** [comment]
Well im waiting for the tag :)
